apiVersion: th2.exactpro.com/v1
kind: Th2Box
metadata:
  name: act
spec:
  image-name: test
  image-version: tet
  type: th2-act
  extended-settings:
    service:
      enabled: false
    resources:
      limits:
        memory: 200Mi
        cpu: 200m
      requests:
        memory: 110Mi
        cpu: 50m
