kind: SettingsFile
metadata:
  name: infra-mgr-config
spec:
  k8s-propagation: rule
  # cradle:
  #   keyspace: cassandratest
  #   host: th2-test3-cassandra01
  #   port: 9042
  #   dataCenter: DC1
  #   username: th2
  #   useCustomPassword: true
  cradle:
    keyspace: checkdata
    host: srt-cassandra01
    port: 9042
    dataCenter: srt
    username: cassandra
    useCustomPassword: true
#  values for k8s-propagation property:
#
#    off  - No synchronization will be done
#    deny - No synchronization will be done and associated namespace will be removed from kubernetes
#    sync - Synchronizes repository changes with kubernetes
#    rule - Synchronizes repository changes with kubernetes and watches resource changes in kubernetes and 
#           brings them back to repository state
#
#  cradle:
#    keyspace: checkdata
  bookConfig:
    defaultBook: "batch"
  th2BoxConfig:
    mqRouter:
      connectionTimeout: -1
      connectionCloseTimeout: 10000
      maxRecoveryAttempts: 5
    grpcRouter:
      workers: 5
    cradleManager:
      connectionCloseTimeout: 1000
    logging:
      logLevelTh2: TRACE
      logLevelRoot: DEBUG
