kind: SettingsFile
metadata:
  name: infra-mgr-config
spec:
  k8s-propagation: deny
  th2BoxConfig:
    logging:
      logLevelTh2: DEBUG
      logLevelRoot: INFO
    mqRouter:
      connectionTimeout: "-1"
      connectionCloseTimeout: "10000"
      maxRecoveryAttempts: "5"
      minConnectionRecoveryTimeout: "10000"
      maxConnectionRecoveryTimeout: "6000"
      prefetchCount: "10"
    grpcRouter:
      workers: "5"
    cradleManager:
      connectionTimeout: "-1"
      connectionCloseTimeout: "10000"
      pageSize: 5000
#
#  values for k8s-propagation property:
#
#    off  - No synchronization will be done
#    deny - No synchronization will be done and associated namespace will be removed from kubernetes
#    sync - Synchronizes repository changes with kubernetes
#    rule - Synchronizes repository changes with kubernetes and watches resource changes in kubernetes and
#           brings them back to repository state
#
