kind: SettingsFile
metadata:
  name: infra-mgr-config
spec:
  th2BoxConfig:
    mqRouter:
      connectionTimeout: -1
      connectionCloseTimeout: 10000
      maxRecoveryAttempts: 5
      minConnectionRecoveryTimeout: 10000
      maxConnectionRecoveryTimeout: 6000
      prefetchCount: 10
    grpcRouter:
      workers: 5
    cradleManager:
      connectionTimeout: -1
      connectionCloseTimeout: 10000
      pageSize: 5000
    logging:
      logLevelTh2: DEBUG
      logLevelRoot: INFO
  k8s-propagation: rule
