kind: SettingsFile
metadata:
  name: infra-mgr-config
spec:
  cradle:
    keyspace: "testsmoke"
  k8s-propagation: rule
  bookConfig:
    defaultBook: "defaultBook-schema"
  th2BoxConfig:
    mqRouter:
      connectionTimeout: -1
      connectionCloseTimeout: 10000
      maxRecoveryAttempts: 5
    grpcRouter:
      workers: 5
    cradleManager:
      connectionCloseTimeout: 1000
    logging:
      logLevelTh2: TRACE
      logLevelRoot: DEBUG
