kind: SettingsFile
metadata:
  name: infra-mgr-config
spec:
  k8s-propagation: rule
  bookConfig:
    defaultBook: "smoke"
  cradle:
    keyspace: smoke
    host: th2-schema-test
    port: 31245
    dataCenter: datacenter1
    username: cassandra
    useCustomPassword: true
  # cradle:
  #   keyspace: regression
  #   host: srt-cassandra01
  #   port: 9042
  #   dataCenter: srt
  #   username: cassandra
  #   useCustomPassword: true

  th2BoxConfig:
    mqRouter:
      # maxRecoveryAttempts: 6
      # minConnectionRecoveryTimeout: 6
      # prefetchCount: 6
      # maxConnectionRecoveryTimeout: 6
      # connectionTimeout: 6
      # connectionCloseTimeout: 6
    # grpcRouter:
      # workers: 1
      # maxRecoveryAttempts: 16

    # cradleManager:
    #   connectionCloseTimeout: 66
    #   pagesize: 6666

    logging:
      logLevelTh2: TRACE
      logLevelRoot: DEBUG
