kind: SettingsFile
metadata:
  name: infra-mgr-config
spec:
  k8s-propagation: deny
  cradle: 
    keyspace: test3
  bookConfig:
    defaultBook: "demo_book_1"
  th2BoxConfig:
    mqRouter:
      connectionTimeout: -1
      connectionCloseTimeout: 10000
      maxRecoveryAttempts: 5
    grpcRouter:
      workers: 5
    cradleManager:
      connectionCloseTimeout: 1000
    logging:
      logLevelTh2: DEBUG
      logLevelRoot: DEBUG
