kind: SettingsFile
metadata:
  name: infra-mgr-config
spec:
  th2BoxConfig:
    mqRouter:
      connectionTimeout: -1
      connectionCloseTimeout: 10000
      maxRecoveryAttempts: 5
      minConnectionRecoveryTimeout: 10001
      maxConnectionRecoveryTimeout: 60000
      prefetchCount: 100
    grpcRouter:
      workers: 5
    cradleManager:
      connectionTimeout: -1
      connectionCloseTimeout: 10000
      pageSize: 5000
    logging:
      logLevelTh2: DEBUG
      logLevelRoot: INFO
  cradle:
    port: 0
    useCustomPassword: false
  k8s-propagation: deny
