apiVersion: th2.exactpro.com/v1
kind: Th2Box
metadata:
  name: act-fix
spec:
  image-name: ghcr.io/th2-net/th2-act-template-j
  image-version: 3.5.0
  type: th2-act
  pins:
  - name: server
    connection-type: grpc-server
    service-classes:
    - com.exactpro.th2.act.grpc.ActService
  - name: to_check1
    connection-type: grpc-client
    service-class: com.exactpro.th2.check1.grpc.Check1Service
  - name: from_codec
    connection-type: mq
    attributes:
    - first
    - oe
    - subscribe
    - parsed
  - name: to_send
    connection-type: mq
    attributes:
    - publish
    - parsed
  extended-settings:
    service:
      enabled: true
      type: LoadBalancer
      endpoints:
      - name: grpc
        targetPort: 8080
        nodePort: 31278
    envVariables:
      JAVA_TOOL_OPTIONS: -XX:+ExitOnOutOfMemoryError
    resources:
      limits:
        memory: 200Mi
        cpu: 200m
      requests:
        memory: 100Mi
        cpu: 20m
