apiVersion: th2.exactpro.com/v2
kind: Th2Box
metadata:
  name: act-fix
spec:
  imageName: ghcr.io/th2-net/th2-act-template-j
  imageVersion: 3.5.0
  type: th2-act
  extendedSettings:
    envVariables:
      JAVA_TOOL_OPTIONS: -XX:+ExitOnOutOfMemoryError
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 20m
        memory: 100Mi
    service:
      enabled: true
      nodePort:
      - name: grpc
        containerPort: 8080
        exposedPort: 31278
  pins:
    mq:
      subscribers:
      - name: from_codec
        attributes:
        - first
        - oe
        - subscribe
        - parsed
      publishers:
      - name: to_send
        attributes:
        - publish
        - parsed
        linkTo:
        - box: codec-fix
          pin: in_codec_encode
    grpc:
      client:
      - name: to_check1
        serviceClass: com.exactpro.th2.check1.grpc.Check1Service
        linkTo:
        - box: check1
          pin: server
      server:
      - name: server
        serviceClasses:
        - com.exactpro.th2.act.grpc.ActService
