apiVersion: th2.exactpro.com/v2
kind: Th2Box
metadata:
  name: act
spec:
  disabled: false
  imageName: ghcr.io/th2-net/th2-act-template-j
  imageVersion: 4.0.0-th2-2150-books-pages-3757835788-8df00f5
  type: th2-act
  pins:
    mq:
      subscribers:
      - name: from_codec
        attributes:
        - first
        - oe
        - parsed
        linkTo:
          - box: codec-fix
            pin: out_codec_decode
      publishers:
      - name: to_send
        attributes:
        - parsed
    grpc:
      client:
      - name: to_check1
        serviceClass: com.exactpro.th2.check1.grpc.Check1Service
        linkTo:
          - box: check1
            pin: server
      server:
      - name: server
        serviceClasses:
        - com.exactpro.th2.act.grpc.ActService
  mqRouter:
    connectionCloseTimeout: 15000
  grpcRouter:
    workers: 6
  extendedSettings:
    entryPoint:
      command:
        - cmd1
        - cmd2
      args:
        - arg1
        - arg2
    service:
      enabled: true
      nodePort:
        - name: grpc
          exposedPort: 31620
          containerPort: 8080
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 200m
        memory: 201Mi
