apiVersion: th2.exactpro.com/v2
kind: Th2Box
metadata:
  name: arfq02fix30
spec:
  imageName: ghcr.io/th2-net/th2-conn-fix
  imageVersion: 4.0.0-th2-3987-dictionaries-custom-config-2789937242
#  versionRange: '4.+'
  type: th2-conn
  # bookName: testbooks
  customConfig:
    session-alias: arfq02fix30
    workspace: /home/sailfish/workspace
    type: th2_service:FIX_Client
    name: arfq02fix30
    dictionaries:
      MAIN: "${dictionary_link:fix50-generic}"
    settings:
      autoStartable: true
      expectedTimeOfStarting: 2000
      invertStoredMessageTypes: false
      performDump: false
      persistMessages: true
      waitingTimeBeforeStarting: 0
      allowUnknownMsgFields: false
      beginString: FIXT.1.1
      checkLatency: false
      defaultApplVerID: 9
      duplicateTagsAllowed: false
      endTime: 00:00:00
      fileStorePath: store/fix/sessions
      logHeartbeats: false
      maxLatency: 120
      microsecondsInTimeStampFields: false
      millisecondsInTimeStampFields: true
      orderingFields: false
      receiveLimit: 0
      rejectInvalidMessage: true
      resetOnDisconnect: false
      resetOnLogout: false
      senderCompID: ARFQ02FIX30
      password: mit123
      startTime: 00:00:00
      targetCompID: FGW
      useLocalTime: false
      useSSL: false
      validateFieldsHaveValues: true
      validateFieldsOutOfOrder: true
      validateFieldsOutOfRange: true
      validateSequenceNumbers: true
      validateUserDefinedFields: true
      addNextExpectedMsgSeqNum: false
      autorelogin: true
      doLogonOnStart: true
      encryptPassword: false
      fakeResendRequest: true
      heartBtInt: 5
      idleTimeout: 0
      ignoreAbsenceOf141tag: false
      logonTimeout: 10
      logoutTimeout: 10
      performanceMode: false
      reconnectInterval: 5
      requiresOrigSendingTime: true
      resetSeqNumFlag: true
      seqNumSender: 0
      seqNumTarget: 0
      socketConnectHost: th2-lseqa05a
      socketConnectPort: 15551
      useDefaultApplVerID: true
  extendedSettings:
    replicas: 0
    envVariables:
      JAVA_TOOL_OPTIONS: -XX:+ExitOnOutOfMemoryError
    resources:
      limits:
        cpu: 220m
        memory: 220Mi
      requests:
        cpu: 20m
        memory: 100Mi
    service:
      enabled: false
  pins:
    mq:
      subscribers:
      - name: in_raw
        attributes:
        - first
        - raw
      - name: fix_to_send
        attributes:
        - send
        # - raw
        - event
        - group
        linkTo:
          - box: codec-fix
            pin: out_codec_encode
      publishers:
      - name: out_raw
        attributes:
        - second
        # - raw
        - publish
        - store
        # - event
        # - group
        filters:
        - metadata:
          - expectedValue: arfq02fix30
            fieldName: session_alias
            operation: EQUAL
