apiVersion: th2.exactpro.com/v2
kind: Th2Box
metadata:
  name: check1
spec:
  imageName: ghcr.io/th2-net/th2-check1
  imageVersion: 4.0.0-th2-2150-books-pages-2648452308
  type: th2-check1
  bookName: m_52
  disabled: false
  customConfig:
    message-cache-size: 1000
    cleanup-older-than: 60
    cleanup-time-unit: SECONDS
  extendedSettings:
    envVariables:
      JAVA_TOOL_OPTIONS: -XX:+ExitOnOutOfMemoryError -XX:+UseContainerSupport -XX:MaxRAMPercentage=85
    resources:
      limits:
        cpu: 200m
        memory: 300Mi
      requests:
        cpu: 50m
        memory: 100Mi
    service:
      enabled: true
      nodePort:
      - name: grpc
        exposedPort: 31224
        containerPort: 8080
      # - name: second
      #   exposedPort: 31720
      #   containerPort: 8081
      clusterIP:
        - name: gui
          containerPort: 8080
      loadBalancer:
        - name: grpc
          containerPort: 8080  
  pins:
    mq:
      subscribers:
      - name: from_codec
        attributes:
        - subscribe
        - parsed
        linkTo:
          - box: codec-fix
            pin: out_codec_decode
      publishers:
    grpc:
      server:
      - name: server
        serviceClasses:
        - com.exactpro.th2.check1.Check1Service
        - com.exactpro.th2.act.actServer
        - com.exactpro.th2.check1.grpc.Check1Service
