apiVersion: th2.exactpro.com/v2
kind: Th2Box
metadata:
  annotations:
    key: value
    key2: value
  name: check1
spec:
  imageName: ghcr.io/th2-net/th2-check1
  imageVersion: 3.9.0
  type: th2-check1
  customConfig:
    message-cache-size: 1000
    cleanup-older-than: 60
    cleanup-time-unit: SECONDS
    rule-execution-timeout: 7000
    time-precision: PT0.000000001S
    decimal-precision: 0.001
    check-null-value-as-empty: false
  extendedSettings:
    envVariables:
      JAVA_TOOL_OPTIONS: -XX:+ExitOnOutOfMemoryError -XX:+UseContainerSupport -XX:MaxRAMPercentage=85
    resources:
      limits:
        cpu: 200m
        memory: 600Mi
      requests:
        cpu: 50m
        memory: 100Mi
    service:
      enabled: true
      nodePort:
      - name: grpc
        containerPort: 8080
        exposedPort: 31279
  pins:
    mq:
      subscribers:
      - name: from_codec
        attributes:
        - subscribe
        - parsed
        linkTo:
        - box: codec-fix
          pin: out_codec_decode
    grpc:
      server:
      - name: server
        serviceClasses:
        - com.exactpro.th2.check1.grpc.Check1Service
  loggingConfig: |
    log4j.rootLogger=INFO, CON
    log4j.appender.CON=org.apache.log4j.ConsoleAppender
    log4j.appender.CON.layout=org.apache.log4j.PatternLayout
    log4j.appender.CON.layout.ConversionPattern=%d{dd MMM yyyy HH:mm:ss,SSS} %-6p [%-15t] %c - %m%n
    log4j.logger.com.exactpro.th2.readlog.impl.RegexpContentParser=INFO
    log4j.logger.com.exactpro.th2=INFO
