apiVersion: th2.exactpro.com/v2
kind: Th2Box
metadata:
  name: codec-fix
spec:
  imageName: ghcr.io/th2-net/th2-codec-fix
  imageVersion: 3.10.4
  type: th2-codec
  customConfig:
    outgoingEventBatchBuildTime: 1
    maxOutgoingEventBatchSize: 99
    numOfEventBatchCollectorWorkers: 1
    codecClassName: com.exactpro.sf.externalapi.codec.impl.ExternalFixCodecFactory
    genericFixDictionary: "${dictionary_link:fix50-generic}"
    dictionaryMap:
      dict_for_msg_a: "${dictionary_link:fix50-generic}"
      dict_for_msg_b: "${dictionary_link:fix50-trm2}"
    subStructure:
      genericFixDictionary: "${dictionary_link:fix50-generic}"
      subStructure:
        genericFixDictionary: "${dictionary_link:fix50-generic}"
        dictionaryMap:
          dict_for_msg_a: "${dictionary_link:fix50-generic}"
          dict_for_msg_b: "${dictionary_link:fix50-trm2}"
    dictionaries:
      MAIN2: "${dictionary_link:fix50-trm2}"
      MAIN: "${dictionary_link:fix50-generic}"
  extendedSettings:
    envVariables:
      JAVA_TOOL_OPTIONS: -XX:+ExitOnOutOfMemoryError -XX:+UseContainerSupport -XX:MaxRAMPercentage=85
    resources:
      limits:
        cpu: 250m
        memory: 250Mi
      requests:
        cpu: 20m
        memory: 100Mi
    service:
      enabled: false
  pins:
    mq:
      subscribers:
      - name: in_codec_encode
        attributes:
        - encoder_in
        - parsed
        - subscribe
        linkTo:
        - box: act-fix
          pin: to_send
      - name: in_codec_decode
        attributes:
        - decoder_in
        - raw
        - subscribe
        linkTo:
        - box: demo-conn1
          pin: in_raw
        - box: demo-conn1
          pin: out_raw
        - box: read-log
          pin: read_log_demo_out
      - name: in_codec_general_encode
        attributes:
        - general_encoder_in
        - parsed
        - subscribe
      - name: in_codec_general_decode
        attributes:
        - general_decoder_in
        - raw
        - subscribe
        linkTo:
        - box: rpt-data-provider
          pin: to_codec_fix
      publishers:
      - name: out_codec_encode
        attributes:
        - encoder_out
        - raw
        - publish
      - name: out_codec_decode
        attributes:
        - decoder_out
        - parsed
        - publish
      - name: out_codec_general_encode
        attributes:
        - general_encoder_out
        - raw
        - publish
      - name: out_codec_general_decode
        attributes:
        - general_decoder_out
        - parsed
        - publish
