apiVersion: th2.exactpro.com/v2
kind: Th2Box
metadata:
  name: demo-dc1
spec:
  imageName: ghcr.io/th2-net/th2-conn-fix
  imageVersion: 3.7.2-th2-3799-2469558886
  type: th2-conn
  customConfig:
    session-alias: demo-dc1
    workspace: /home/sailfish/workspace
    type: th2_service:FIX_Client
    name: demo-dc1
    settings:
      autoStartable: true
      expectedTimeOfStarting: 2000
      invertStoredMessageTypes: false
      performDump: false
      persistMessages: true
      waitingTimeBeforeStarting: 0
      allowUnknownMsgFields: false
      beginString: FIXT.1.1
      checkLatency: false
      defaultApplVerID: 9
      duplicateTagsAllowed: false
      endTime: 00:00:00
      fileStorePath: store/fix/sessions
      logHeartbeats: false
      maxLatency: 120
      microsecondsInTimeStampFields: false
      millisecondsInTimeStampFields: true
      orderingFields: false
      receiveLimit: 0
      rejectInvalidMessage: false
      resetOnDisconnect: false
      resetOnLogout: false
      senderCompID: DEMO-DC1
      startTime: 00:00:00
      targetCompID: FGW
      useLocalTime: false
      useSSL: false
      validateFieldsHaveValues: true
      validateFieldsOutOfOrder: true
      validateFieldsOutOfRange: true
      validateSequenceNumbers: true
      validateUserDefinedFields: true
      addNextExpectedMsgSeqNum: false
      autorelogin: true
      doLogonOnStart: true
      encryptPassword: false
      fakeResendRequest: true
      heartBtInt: 30
      idleTimeout: 0
      ignoreAbsenceOf141tag: false
      logonTimeout: 10
      logoutTimeout: 10
      performanceMode: false
      reconnectInterval: 5
      requiresOrigSendingTime: true
      resetSeqNumFlag: true
      seqNumSender: 0
      seqNumTarget: 0
      socketConnectHost: dc-demo-server1
      socketConnectPort: 8080
      useDefaultApplVerID: true
  extendedSettings:
    envVariables:
      JAVA_TOOL_OPTIONS: |
        -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=1099 -Dcom.sun.management.jmxremote.rmi.port=1099 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=127.0.0.1 -XX:+ExitOnOutOfMemoryError -XX:+UseContainerSupport -XX:MaxRAMPercentage=85
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 20m
        memory: 100Mi
    service:
      enabled: true
  pins:
    mq:
      subscribers:
      - name: fix_to_send
        attributes:
        - send
        - raw
        - subscribe
        filters:
        - metadata:
          - expectedValue: demo-dc1
            fieldName: session_alias
            operation: EQUAL
      publishers:
      - name: in_raw
        attributes:
        - first
        - raw
        - publish
        - store
      - name: out_raw
        attributes:
        - second
        - raw
        - publish
        - store
