apiVersion: th2.exactpro.com/v1
kind: Th2Box
metadata:
  name: read-log
spec:
  image-name: ghcr.io/th2-net/th2-read-log
  image-version: stub
  type: th2-read
  custom-config:
    logDirectory: "${user.home}/demo_outputs/"
    aliases:
      demo-log:
        regexp: "8=FIX.+10=.+\\b\\u0001"
        pathFilter: ".*log_test.*"
        groups: [0]
  pins:
    - name: read_log_demo_out
      connection-type: mq
      attributes:
        - raw
        - publish
        - store
  extended-settings:
    externalBox:
      enabled: true
    service:
      enabled: false
    envVariables:
      JAVA_TOOL_OPTIONS: "-XX:+ExitOnOutOfMemoryError"
    resources:
      limits:
        memory: 200Mi
        cpu: 200m
      requests:
        memory: 100Mi
        cpu: 20m
  prometheus:
    enabled: false