apiVersion: th2.exactpro.com/v2
kind: Th2Box
metadata:
  name: script-entry-point
spec:
  imageName: dev-script
  imageVersion: dev-script
  type: th2-script
  extendedSettings:
    externalBox:
      enabled: true
    service:
      enabled: false
  pins:
    grpc:
      client:
      - name: to_act
        serviceClass: com.exactpro.th2.act.grpc.ActService
        linkTo:
        - box: act-fix
          pin: server
      - name: to_check1
        serviceClass: com.exactpro.th2.check1.grpc.Check1Service
        linkTo:
        - box: check1
          pin: server
