apiVersion: th2.exactpro.com/v2
kind: Th2Box
metadata:
  name: script
spec:
  imageName: dev-script
  imageVersion: dev-script
  type: th2-script
  extendedSettings:
    externalBox:
      address: kos101
      enabled: true
      endpoints:
      - name: grpc
        targetPort: 3333
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 51m
        memory: 100Mi
    service:
      enabled: false
  pins:
    mq:
      subscribers:
      publishers:
      - name: msg_raw
        attributes:
        - first
        - raw
        - publish
        - store
        - to_mstore
    grpc:
      client:
      - name: to_act
        serviceClass: com.exactpro.th2.act.grpc.ActService
        attributes:
        - to_act
      - name: to_verifier
        serviceClass: com.exactpro.th2.check1.grpc.Check1Service
        attributes:
        - to_verifier
      - name: to_sim
        serviceClass: com.exactpro.th2.check1.grpc.Check1Service
        linkTo:
          - box: sim
            pin: server
        attributes:
        - to_sim



