apiVersion: th2.exactpro.com/v2
kind: Th2Box
metadata:
  name: sim
spec:
  imageName: ghcr.io/th2-net/th2-sim-template
  imageVersion:   4.0.0-TH2-3877-build-2650479630
  type: th2-sim
  customConfig:
    defaultRules:
    - methodName: createDemoRule
      enable: true
      settings:
        connection_id:
          session_alias: fix-server
  extendedSettings:
    envVariables:
      # JAVA_TOOL_OPTIONS: -XX:+ExitOnOutOfMemoryError
      JAVA_TOOL_OPTIONS: -XX:+ExitOnOutOfMemoryError -XX:UseSSE=2
    resources:
      limits:
        cpu: 200m
        memory: 202Mi
      requests:
        cpu: 20m
        memory: 100Mi
    service:
      enabled: true
      nodePort:
      - name: grpc
        exposedPort: 31536
        containerPort: 8080
  pins:
    mq:
      subscribers:
      - name: subscribe
        attributes:
        - first
        - subscribe
        - parsed
      publishers:
      - name: send1
        attributes:
        - second
        - publish
        - parsed
        - fix-server
      - name: send2
        attributes:
        - second
        - publish
        - parsed
        - fix-demo-server2
      - name: send3
        attributes:
        - second
        - publish
        - parsed
        - dc-demo-server1
      - name: send4
        attributes:
        - second
        - publish
        - parsed
        - dc-demo-server2
    grpc:
      server:
      - name: server
        serviceClasses:
        - com.exactpro.th2.check1.grpc.Check1Service
