apiVersion: th2.exactpro.com/v1
kind: Th2Box
metadata:
  name: util
spec:
  image-name: ghcr.io/th2-net/th2-util
  image-version: 3.1.0
  type: th2-util
  pins:
    - name: server
      connection-type: grpc-server
      service-classes:
        - com.exactpro.th2.util.grpc.MessageComparatorService
  extended-settings:
    service:
      enabled: true
    envVariables:
      JAVA_TOOL_OPTIONS: "-XX:+ExitOnOutOfMemoryError"
    resources:
      limits:
        memory: 200Mi
        cpu: 200m
      requests:
        memory: 100Mi
        cpu: 20m