apiVersion: th2.exactpro.com/v1
kind: Th2Link
metadata:
  name: links
spec:
  boxes-relation:
    router-grpc:
      - name: script-to-act
        from:
          box: script-entry-point
          pin: to_act
        to:
          box: template-instance
          pin: send-fix-message
      - name: codec-fix-to-recon
        from:
          box: template-instance
          pin: subscribe-parsed-messages
        to:
          box: recon
          pin: incoming
      - name: recon-to-util
        from:
          box: recon
          pin: to_util
        to:
          box: template-instance
          pin: util
