apiVersion: th2.exactpro.com/v1
kind: Th2Link
metadata:
  name: links
spec:
  boxes-relation:
    router-mq:
#########CodecPerfChecker#######
      - name: codec-perf-checker-to_encoder
        from:
          box: codec-perf-checker
          pin: to_encoder
        to:
          box: codec-under-test
          pin: in_codec_encode