apiVersion: th2.exactpro.com/v1
kind: Th2Link
metadata:
  name: links
spec:
  multi-dictionaries-relation:
    - name: codec-fix-multi-dictionary
      box: codec-fix
      dictionaries:
        - name: fix50-generic
          alias: fix50-generic-alias
        - name: fix50-trm2
          alias: fix50-trm2-alias
    - name: demo-conn1-multi-dictionary
      box: demo-conn1
      dictionaries:
        - name: fix50-generic
          alias: fix50-generic-alias
  dictionaries-relation:
####### MAIN
  - name: codec-fix-dictionary
    box: codec-fix
    dictionary:
      name: fix50-generic
      type: MAIN
  - name: demo-conn1-dictionary
    box: demo-conn1
    dictionary:
      name: fix50-generic
      type: MAIN
  - name: server1-dictionary
    box: fix-demo-server1
    dictionary:
      name: fix50-generic
      type: MAIN
####### LEVEL1
  - name: demo-conn-dic-2
    box: demo-conn1
    dictionary:
      name: fix50-trm2
      type: LEVEL1
#######################################################
  boxes-relation:
    router-mq:
######## codec and act
    - name: act-to-codec
      from:
        box: act-fix
        pin: to_send
      to:
        box: codec-fix
        pin: in_codec_encode
    - name: codec-to-act
      from:
        box: codec-fix
        pin: out_codec_decode
      to:
        box: act-fix
        pin: from_codec

######## codec and check1
    - name: codec-to-check1
      from:
        box: codec-fix
        pin: out_codec_decode
      to:
        box: check1
        pin: from_codec

######## codec and recon
    - name: codec-fix-to-recon
      from:
        box: codec-fix
        pin: out_codec_decode
      to:
        box: recon
        pin: incoming

######## codec and provider
    - name: provider-to-codec
      from:
        box: rpt-data-provider
        pin: to_codec_fix
      to:
        box: codec-fix
        pin: in_codec_general_decode
    - name: codec-to-provider
      from:
        box: codec-fix
        pin: out_codec_general_decode
      to:
        box: rpt-data-provider
        pin: from_codec

######## codec and demo-conn1
    - name: codec-to-demo-conn1
      from:
        box: codec-fix
        pin: out_codec_encode
      to:
        box: demo-conn1
        pin: fix_to_send
    - name: demo-conn1-to-codec
      from:
        box: demo-conn1
        pin: in_raw
      to:
        box: codec-fix
        pin: in_codec_decode
    - name: demo-conn1_out-codec
      from:
        box: demo-conn1
        pin: out_raw
      to:
        box: codec-fix
        pin: in_codec_decode

######## codec and demo-conn1
    - name: readlog-to-codec
      from:
        box: read-log
        pin: read_log_demo_out
      to:
        box: codec-fix
        pin: in_codec_decode
    router-grpc:
    - name: act-to-check1
      from:
        box: act-fix
        pin: to_check1
      to:
        box: check1
        pin: server
    - name: recon-to-util
      from:
        box: recon
        pin: to_util
      to:
        box: util
        pin: server
    - name: script-to-act
      from:
        box: script-entry-point
        pin: to_act
      to:
        box: act-fix
        pin: server
    - name: script-to-check1
      from:
        box: script-entry-point
        pin: to_check1
      to:
        box: check1
        pin: server
