apiVersion: th2.exactpro.com/v1
kind: Th2CoreBox
metadata:
  name: act-ui
spec:
  image-name: ghcr.io/th2-net/th2-act-ui
  image-version: 1.0.17
  type: th2-rpt-viewer
  extended-settings:
    service:
      enabled: true
      type: NodePort
      endpoints:
        - name: 'other'
          targetPort: 80
          nodePort: 31256
    envVariables:
      JAVA_TOOL_OPTIONS: "-XX:+ExitOnOutOfMemoryError"
    resources:
      limits:
        memory: 300Mi
        cpu: 210m
      requests:
        memory: 100Mi
        cpu: 20m