apiVersion: th2.exactpro.com/v1
kind: Th2Estore
metadata:
  name: estore
spec:
  image-name: ghcr.io/th2-net/th2-estore
  image-version: 3.6.0
  custom-config:
    cradleInstanceName: instance1
  extended-settings:
    service:
      enabled: false
    resources:
      limits:
        memory: 500Mi
        cpu: 100m
      requests:
        memory: 100Mi
        cpu: 20m