apiVersion: th2.exactpro.com/v2
kind: Th2Estore
metadata:
  name: estore
spec:
  disabled: false
  imageName: ghcr.io/th2-net/th2-estore
  imageVersion: 5.0.0-dev-version-5-4891158135-2fb71cd
  pins:
    mq:
      subscribers:
        - name: transport
          attributes:
            - transport-event
            - subscribe
          linkTo:
            - box: woodpecker1
              pin: out_messages
            - box: woodpecker2
              pin: out_messages
  customConfig:
    maxTaskCount : 128
    maxTaskDataSize : 268435456
    maxRetryCount : 3
  mqRouter:
    prefetchCount: 100
  extendedSettings:
    envVariables:
      JAVA_TOOL_OPTIONS: >
        -XX:+ExitOnOutOfMemoryError
        -XX:+UseContainerSupport
        -Dlog4j2.shutdownHookEnabled=false
        -XX:MaxRAMPercentage=50
        -Ddatastax-java-driver.advanced.connection.init-query-timeout="5000 milliseconds"
        -Ddatastax-java-driver.basic.request.timeout="3 seconds"
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.port=2099
        -Dcom.sun.management.jmxremote.rmi.port=2099
        -Dcom.sun.management.jmxremote.ssl=false
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.local.only=false
        -Djava.rmi.server.hostname=127.0.0.1
    resources:
      limits:
        cpu: 2001m
        memory: 502Mi
      requests:
        cpu: 1000m
        memory: 100Mi
    service:
      enabled: true
