apiVersion: th2.exactpro.com/v2
kind: Th2Mstore
metadata:
  name: mstore
spec:
  imageName: ghcr.io/th2-net/th2-mstore
  imageVersion: 3.5.0
  extendedSettings:
    resources:
      limits:
        cpu: 100m
        memory: 500Mi
      requests:
        cpu: 20m
        memory: 100Mi
    service:
      enabled: false
