apiVersion: th2.exactpro.com/v2-2
kind: Th2Mstore
metadata:
  name: mstore
spec:
  imageName: ghcr.io/th2-net/th2-mstore
  imageVersion: 5.0.0-dev-version-5-4375917515-3aba37a #5.0.0-dev-version-5-4301443649-995d6b6 #5.0.0-dev-version-5-4282356799-22dca98 #5.0.0-dev-version-5-4301443649-995d6b6
  extendedSettings:
    envVariables:
      JAVA_TOOL_OPTIONS: -XX:+ExitOnOutOfMemoryError -Ddatastax-java-driver.advanced.connection.init-query-timeout="5000
        milliseconds"
    resources:
      limits:
        cpu: 1000m
        memory: 1000Mi
      requests:
        cpu: 200m
        memory: 200Mi
    service:
      enabled: false
