apiVersion: th2.exactpro.com/v2
kind: Th2CoreBox
metadata:
  name: rpt-data-provider
spec:
  imageName: ghcr.io/th2-net/th2-rpt-data-provider
  imageVersion: 5.0.15
  type: th2-rpt-data-provider
  customConfig:
    hostname: localhost
    port: 8080
    responseTimeout: 60000
    serverCacheTimeout: 60000
    clientCacheTimeout: 60
    eventCacheSize: 100000
    messageCacheSize: 100000
    ioDispatcherThreadPoolSize: 15
    codecCacheSize: 1000
    codecBatchesCacheSize: 200
    maxMessagesLimit: 5000
    messageSearchPipelineBuffer: 2000
    rabbitBatchMergeBuffer: 2000
    rabbitMergedBatchSize: 128
    decodeMessageConsumerCount: 16
    cradleDispatcherPoolSize: 15
    eventSearchChunkSize: 10000
  extendedSettings:
    envVariables:
      JAVA_TOOL_OPTIONS: -XX:+ExitOnOutOfMemoryError -Ddatastax-java-driver.advanced.connection.init-query-timeout="5000
        milliseconds" -XX:+UseContainerSupport -XX:MaxRAMPercentage=85
    resources:
      limits:
        cpu: 600m
        memory: 2000Mi
      requests:
        cpu: 20m
        memory: 300Mi
    service:
      enabled: true
      nodePort:
      - name: grpc
        containerPort: 8080
        exposedPort: 30289
  pins:
    mq:
      subscribers:
      - name: from_codec
        attributes:
        - from_codec
        - parsed
        - subscribe
      publishers:
      - name: to_codec_fix
        attributes:
        - to_codec
        - raw
        - publish
        - fix-demo-server1
        - fix-demo-server2
        - dc-demo-server1
        - fix-demo-server2
        - demo-conn1
        - demo-conn2
        - demo-dc1
        - demo-dc2
        - demo-log
        linkTo:
        - box: codec-fix
          pin: in_codec_general_decode
      - name: to_codec_csv
        attributes:
        - to_codec
        - raw
        - publish
        - demo-csv
