apiVersion: th2.exactpro.com/v2
kind: Th2CoreBox
metadata:
  name: rpt-data-viewer
spec:
  imageName: ghcr.io/th2-net/th2-rpt-viewer
  imageVersion: 3.1.56
  type: th2-rpt-viewer
  extendedSettings:
    resources:
      limits:
        cpu: 600m
        memory: 200Mi
      requests:
        cpu: 20m
        memory: 100Mi
    service:
      enabled: true
  prometheus:
    enabled: true
