apiVersion: th2.exactpro.com/v2
kind: Th2CoreBox
metadata:
  name: rpt-data-provider
spec:
  imageName: ghcr.io/th2-net/th2-rpt-data-provider
  imageVersion: 5.4.18-master_migration_to_cradle_rebase-3368544789
  type: th2-rpt-data-provider
  customConfig:
    hostname: localhost
    port: 8080
    responseTimeout: 60000
    serverCacheTimeout: 60000
    eventCacheSize: 100000
    messageCacheSize: 100000
    ioDispatcherThreadPoolSize: 1
  extendedSettings:
    envVariables:
      JAVA_TOOL_OPTIONS: -XX:+ExitOnOutOfMemoryError -Ddatastax-java-driver.advanced.connection.init-query-timeout="5000
        milliseconds"
    resources:
      limits:
        cpu: 600m
        memory: 1001Mi
      requests:
        cpu: 20m
        memory: 300Mi
    service:
      enabled: true
      nodePort:
      - name: grpc
        exposedPort: 31646
        containerPort: 8080
  pins:
    mq:
      subscribers:
      - name: from_codec
        attributes:
        - from_codec
        - parsed
        - subscribe
      - name: from_codec_codec-fix
        attributes:
        - from_codec
        - parsed
        - subscribe
        - arfq01fix21
        - arfq02fix30
        - arfq02fix31
        - arfq02dc30
        linkTo:
          - box: codec-fix
            pin: out_codec_general_decode
      publishers:
      - name: to_codec_codec-fix
        attributes:
        - to_codec
        - raw
        - publish
        - arfq01fix21
        - arfq02fix30
        - arfq02fix31
        - arfq02dc30
      - name: to_codec
        attributes:
        - to_codec
        - raw
        - publish
        - csvtest1
        - csvtest2
        - csvtest3
        - csvtest5
        - csvtest6
        - csvtest7
