apiVersion: th2.exactpro.com/v2
kind: Th2CoreBox
metadata:
  name: rpt-data-viewer
spec:
  imageName: ghcr.io/th2-net/th2-rpt-viewer
  imageVersion: 5.0.25-books-pages-5-3512403717
  type: th2-rpt-viewer
  extendedSettings:
    resources:
      limits:
        cpu: 50m
        memory: 50Mi
      requests:
        cpu: 50m
        memory: 50Mi
    service:
      enabled: true
      clusterIP:
      - name: gui
        containerPort: 8080
        port: 8080

